const PRESETS = {
  douyin: ["douyin.com", "iesdouyin.com", "amemv.com", "snssdk.com"],
  bilibili: ["bilibili.com"],
};

const presetEl = document.getElementById("preset");
const customSectionEl = document.getElementById("customSection");
const domainsEl = document.getElementById("domains");
const filenameEl = document.getElementById("filename");
const saveAsEl = document.getElementById("saveAs");
const exportBtn = document.getElementById("exportBtn");
const statusEl = document.getElementById("status");

function pad(value) {
  return String(value).padStart(2, "0");
}

function timestamp() {
  const now = new Date();
  return [
    now.getFullYear(),
    pad(now.getMonth() + 1),
    pad(now.getDate()),
    "-",
    pad(now.getHours()),
    pad(now.getMinutes()),
    pad(now.getSeconds()),
  ].join("");
}

function safeFilename(value) {
  return value.replace(/[<>:"/\\|?*\x00-\x1f]/g, "-").replace(/\s+/g, "-");
}

function defaultFilename() {
  return `${presetEl.value}-cookies-${timestamp()}.txt`;
}

function setStatus(message, type = "") {
  statusEl.textContent = message;
  statusEl.className = `status ${type}`.trim();
}

function chromeCall(target, method, ...args) {
  return new Promise((resolve, reject) => {
    target[method](...args, result => {
      const error = chrome.runtime.lastError;
      if (error) {
        reject(new Error(error.message));
        return;
      }
      resolve(result);
    });
  });
}

function sanitizeField(value) {
  return String(value ?? "")
    .replace(/\t/g, "%09")
    .replace(/\r/g, "%0D")
    .replace(/\n/g, "%0A");
}

function cookieToNetscapeLine(cookie) {
  const httpOnlyPrefix = cookie.httpOnly ? "#HttpOnly_" : "";
  const domain = `${httpOnlyPrefix}${cookie.domain}`;
  const includeSubdomains = cookie.hostOnly ? "FALSE" : "TRUE";
  const path = cookie.path || "/";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expires = cookie.session ? "0" : String(Math.floor(cookie.expirationDate || 0));

  return [
    domain,
    includeSubdomains,
    path,
    secure,
    expires,
    sanitizeField(cookie.name),
    sanitizeField(cookie.value),
  ].join("\t");
}

function buildCookiesTxt(cookies, domains) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by Media Studio Cookie Exporter",
    "# Keep this file private. It may grant access to logged-in sessions.",
    `# Domains: ${domains.join(", ")}`,
    `# Exported at: ${new Date().toISOString()}`,
    "",
    ...cookies.map(cookieToNetscapeLine),
    "",
  ];

  return lines.join("\n");
}

function normalizeDomain(value) {
  return value
    .trim()
    .replace(/^https?:\/\//i, "")
    .replace(/^www\./i, "")
    .split("/")[0]
    .split(":")[0]
    .toLowerCase();
}

async function getCurrentTabDomain() {
  const [tab] = await chromeCall(chrome.tabs, "query", { active: true, currentWindow: true });
  if (!tab?.url) {
    throw new Error("Không lấy được URL của tab hiện tại.");
  }

  const url = new URL(tab.url);
  return normalizeDomain(url.hostname);
}

async function getSelectedDomains() {
  const preset = presetEl.value;

  if (preset === "current") {
    return [await getCurrentTabDomain()];
  }

  if (preset === "custom") {
    const domains = domainsEl.value
      .split(/[\n,]/)
      .map(normalizeDomain)
      .filter(Boolean);

    if (domains.length === 0) {
      throw new Error("Vui lòng nhập ít nhất một domain.");
    }

    return [...new Set(domains)];
  }

  return PRESETS[preset] || [];
}

async function getCookiesForDomain(domain) {
  return chromeCall(chrome.cookies, "getAll", { domain });
}

async function collectCookies(domains) {
  const cookieMap = new Map();

  for (const domain of domains) {
    const cookies = await getCookiesForDomain(domain);
    for (const cookie of cookies) {
      const key = [
        cookie.domain,
        cookie.path,
        cookie.name,
        cookie.storeId,
        cookie.partitionKey ? JSON.stringify(cookie.partitionKey) : "",
      ].join("\t");
      cookieMap.set(key, cookie);
    }
  }

  return [...cookieMap.values()].sort((a, b) => {
    const domainCompare = a.domain.localeCompare(b.domain);
    if (domainCompare !== 0) return domainCompare;
    const pathCompare = a.path.localeCompare(b.path);
    if (pathCompare !== 0) return pathCompare;
    return a.name.localeCompare(b.name);
  });
}

async function downloadTextFile(filename, content, saveAs) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  try {
    await chromeCall(chrome.downloads, "download", {
      url,
      filename,
      saveAs,
      conflictAction: "uniquify",
    });
  } finally {
    setTimeout(() => URL.revokeObjectURL(url), 30000);
  }
}

async function exportCookies() {
  exportBtn.disabled = true;
  setStatus("Đang đọc cookies...");

  try {
    const domains = await getSelectedDomains();
    const cookies = await collectCookies(domains);

    if (cookies.length === 0) {
      throw new Error(
        `Không tìm thấy cookie cho: ${domains.join(", ")}.\nHãy mở trang, đăng nhập/refresh rồi thử lại.`
      );
    }

    const filename = safeFilename(filenameEl.value.trim() || defaultFilename());
    const content = buildCookiesTxt(cookies, domains);
    await downloadTextFile(filename, content, saveAsEl.checked);

    setStatus(`Đã export ${cookies.length} cookie vào ${filename}`, "ok");
  } catch (error) {
    setStatus(error.message || String(error), "error");
  } finally {
    exportBtn.disabled = false;
  }
}

function updateUiForPreset() {
  customSectionEl.hidden = presetEl.value !== "custom";
  filenameEl.value = defaultFilename();
}

presetEl.addEventListener("change", updateUiForPreset);
exportBtn.addEventListener("click", exportCookies);
updateUiForPreset();
